#!/usr/bin/env php
<?php
/**
 * This file contains the command line application for the ClamScanWeb app
 * @license MIT
 * @author Anthony Vitacco <avitacco@iu.edu>
 */

/**
 * Require the composer autoloader and the dependency container
 */
require(__dir__ . "/vendor/autoload.php");
require(__dir__ . "/app/resources/dependencyContainer.php");

/**
 * Declare the namespaces this script will use
 */
use Iu\Uits\Webtech\Clam\JobRunner;
use Symfony\Component\Console\Application;

/**
 * Instantiate the console application class
 */
$application = new Application();

/**
 * Add the job runner class to the application
 */
$application->add(new JobRunner($deps));

/**
 *
 */
$application->run();
